name: Scripted maintenance

on: push

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Glob files
      run: python ${{ github.workspace }}/SPID/ProjectGen.py

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: maintenance
